apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: helm-octopus-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from Nginx!</title>
    </head>
    <body>
      <h1>{{ .Values.customMessage }}</h1>
    </body>
    </html>
