apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: helm-octopus-app
spec:
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: "{{ .Values.nginx-port }}"
  type: NodePort
