apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-helm-be
  namespace: multi-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-be
  template:
    metadata:
      labels:
        app: multi-be
    spec:
      containers:
      - name: backend-container
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done"]
        ports:
        - containerPort: 80
